// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-DHYyRLSt5I-m154iBKmxGFG8QQh6aoQ',
    appId: '1:698797538184:web:18913fa42afc346c7b583d',
    messagingSenderId: '698797538184',
    projectId: 'vidaplena-633f8',
    authDomain: 'vidaplena-633f8.firebaseapp.com',
    storageBucket: 'vidaplena-633f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0r6quk8QUN7KHS3bonLmP9Y4S46crT0I',
    appId: '1:698797538184:android:74364d154870e7577b583d',
    messagingSenderId: '698797538184',
    projectId: 'vidaplena-633f8',
    storageBucket: 'vidaplena-633f8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-DHYyRLSt5I-m154iBKmxGFG8QQh6aoQ',
    appId: '1:698797538184:web:5fe943d75e9b4ba77b583d',
    messagingSenderId: '698797538184',
    projectId: 'vidaplena-633f8',
    authDomain: 'vidaplena-633f8.firebaseapp.com',
    storageBucket: 'vidaplena-633f8.firebasestorage.app',
  );
}
